In [1]:
import cv2
import numpy as np

## Load or Read Image

In [2]:
## Load an image using 'imread' specifying the path to image
img=cv2.imread("C:\\Users\\KIRTI RAJ PRADHAN\\Downloads\\Modi.jpg",1)

## Lets take a closer look at how images are stored

In [3]:
print(img)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


## Shape gives the dimensions of the image array

In [4]:
img.shape
# The 3D dimensions are 1358 pixels in height * 1500 pixels wide
# 3 means that there are 3 components (RGB) that make up this image

(1358, 1500, 3)

## Display the image

In [5]:
# To display our image variable, we use 'imshow'
# The first parameter will be the title shown on image window
# The second parameter is image variable
cv2.imshow('PM',img)
cv2.waitKey()
cv2.destroyAllWindows()

In [6]:
img=cv2.imread("C:\\Users\\KIRTI RAJ PRADHAN\\Downloads\\Modi.jpg")
cv2.imshow("PM",img)
cv2.waitKey()
cv2.destroyAllWindows()

## Save Image

In [7]:
cv2.imwrite("pm_b_w.jpg",img)

True

## Resize Image

In [8]:
img=cv2.imread("C:\\Users\\KIRTI RAJ PRADHAN\\Downloads\\Modi.jpg")
resized_image=cv2.resize(img,(500,500))
gray=cv2.cvtColor(resized_image,cv2.COLOR_BGR2GRAY)
cv2.imshow("PM",gray)
cv2.waitKey()
cv2.destroyAllWindows()

In [9]:
img.shape[0]*0.5

679.0

In [10]:
img.shape[1]*0.5

750.0

## Face Detection using HAAR Cascade Classifier

In [11]:
face_classifier=cv2.CascadeClassifier('C:\\Users\\KIRTI RAJ PRADHAN\\Downloads\\haarcascade_frontalface_default.xml')
image=cv2.imread('C:\\Users\\KIRTI RAJ PRADHAN\\Downloads\\Modi.jpg')
image=cv2.resize(img,(500,500))
gray=cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
face=face_classifier.detectMultiScale(gray,1.05,5)

In [12]:
print(face)

[[205  79 217 217]]


In [13]:
face_classifier=cv2.CascadeClassifier('C:\\Users\\KIRTI RAJ PRADHAN\\Downloads\\haarcascade_frontalface_default.xml')
image=cv2.imread('C:\\Users\\KIRTI RAJ PRADHAN\\Downloads\\Modi.jpg')
image=cv2.resize(img,(500,500))
gray=cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
faces=face_classifier.detectMultiScale(gray,1.05,5)
if face is ():
    print("No face found")
for (x,y,w,h) in faces:
    cv2.rectangle(image,(x,y),(x+w,y+h),(0,255,100),)
cv2.imshow('Face detection',image)
cv2.waitKey()
cv2.destroyAllWindows()

<>:6: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:6: SyntaxWarning: "is" with a literal. Did you mean "=="?
C:\Users\KIRTI RAJ PRADHAN\AppData\Local\Temp\ipykernel_26968\2201621446.py:6: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if face is ():


## Face and Eye Detection using HARR Cascade Classifier in image

In [14]:
face_classifier=cv2.CascadeClassifier("C:\\Users\\KIRTI RAJ PRADHAN\\Downloads\\haarcascade_frontalface_default.xml")
eye_classifier=cv2.CascadeClassifier("C:\\Users\\KIRTI RAJ PRADHAN\\Downloads\\haarcascade_eye.xml")
img=cv2.imread("C:\\Users\\KIRTI RAJ PRADHAN\\Downloads\\Modi.jpg")
resize_image=cv2.resize(img,(500,500))
gray=cv2.cvtColor(resize_image,cv2.COLOR_BGR2GRAY)
faces=face_classifier.detectMultiScale(gray,1.3,5)
if faces is ():
    print("Not Face Found")
for (x,y,w,h) in faces:
    cv2.rectangle(resized_image,(x,y),(x+w,y+h),(255,0,0),2)
    roi_gray=gray[y:y+h,x:x+w]
    roi_color=resized_image[y:y+h,x:x+w]
    eyes=eye_classifier.detectMultiScale(roi_gray)
    for (ex,ey,ew,eh) in eyes:
        cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(0,255,0),2)
cv2.imshow('img',resized_image)
cv2.waitKey()
cv2.destroyAllWindows()

<>:7: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:7: SyntaxWarning: "is" with a literal. Did you mean "=="?
C:\Users\KIRTI RAJ PRADHAN\AppData\Local\Temp\ipykernel_26968\184262411.py:7: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if faces is ():


## Capture a Vedio

In [15]:
# Doing some face recognition with the webcam
import cv2
video=cv2.VideoCapture(0) #0--->webcam
while True:
    check, frame = video.read()
    #gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    cv2.imshow('video',frame)
    if cv2.waitKey(1)==ord('q'):
        break
video.release()
cv2.destroyAllWindows()

## Face and Eye Detection using HARR Cascade Classifier in video

In [16]:
face_cascade=cv2.CascadeClassifier("C:\\Users\\KIRTI RAJ PRADHAN\\Downloads\\haarcascade_frontalface_default.xml")
eye_cascade=cv2.CascadeClassifier("C:\\Users\\KIRTI RAJ PRADHAN\\Downloads\\haarcascade_eye.xml")
def detect(gray,frame):
    faces=face_cascade.detectMultiScale(gray,1.3,5)
    for (x,y,w,h) in faces:
        cv2.rectangle(frame,(x,y),(x+w,y+h),(255,0,0),2)
        roi_gray=gray[y:y+h,x:x+w]
        roi_color=frame[y:y+h,x:x+w]
        eyes=eye_cascade.detectMultiScale(roi_gray,1.1,3)
        for (ex,ey,ew,eh) in eyes:
            cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(0,255,0),2)
    return frame
video=cv2.VideoCapture(0) #0--->webcam
while True:
    check, frame = video.read()
    gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    canvas=detect(gray,frame)
    cv2.imshow('video',canvas)
    if cv2.waitKey(1)==ord('q'):  #press the key 'q' then the video will off
        break
video.release()
cv2.destroyAllWindows()

## Predistrian Detection 

In [ ]:
import cv2
body_classifier=cv2.CascadeClassifier("C:\\Users\\KIRTI RAJ PRADHAN\\Downloads\\haarcascade_fullbody.xml")
cap=cv2.VideoCapture("C:\\Users\\KIRTI RAJ PRADHAN\\Downloads\\walking.avi")
while cap.isOpened():
    check,frame=cap.read()
    gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    bodies=body_classifier.detectMultiScale(gray,1.2,3)
    for (x,y,w,h) in bodies:
        cv2.rectangle(frame,(x,y),(x+w,y+h),(255,0,0),2)
        cv2.imshow('Pedestrians',frame)
    if cv2.waitKey(1)==ord('q'):  #press the key 'q' then the video will off
        break
cap.release()
cv2.destroyAllWindows()

In [18]:
import time
car_classifier=cv2.CascadeClassifier("C:\\Users\\KIRTI RAJ PRADHAN\\Downloads\\haarcascade_car.xml")
cap=cv2.VideoCapture("C:\\Users\\KIRTI RAJ PRADHAN\\Downloads\\cars.avi")
while cap.isOpened():
    time.sleep(.05)
    check,frame=cap.read()
    gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    cars=car_classifier.detectMultiScale(gray,1.4,2)
    for (x,y,w,h) in cars:
        cv2.rectangle(frame,(x,y),(x+w,y+h),(0,255,255),2)
        cv2.imshow('cars',frame)
    if cv2.waitKey(1)==ord('q'):  #press the key 'q' then the video will off
        break
cap.release()
cv2.destroyAllWindows()